# 必ずしも起動時に必要でないプラグインは
# 利用条件と共にこちらで入れる

# 補完プラグイン
# インサートモード時に呼び出す
[[plugins]]
repo  = 'Shougo/neocomplete'
on_i  = 1
hook_add = '''
  source ~/.vim/userautoload/plugins/basic/plugin-neocomplete.vim
'''

# 以下のファイルは、環境に併せてコメントを外してインストールすること

# 特定のファイルタイプで読み込む
## Markdown
[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = 'markdown'
