# ~/.tmux.conf

# prefixをCtrl-bのまま使うならこのままでOK
# Ctrl-a派にしたい場合だけ以下を有効化
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# prefixキーの変更
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# マウス操作を有効化
set -g mouse on

# スクロール履歴を増やす
set -g history-limit 100000

# ウィンドウ/ペイン番号を1始まりにする
set -g base-index 1
setw -g pane-base-index 1

# 新しいウィンドウ/ペインを現在のディレクトリで開く
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# vi風キーバインド
setw -g mode-keys vi
## ペイン移動をvim風に
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
## コマンドモードでの選択方法をvim風に変更
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
## クリップボートとの連携
### ☆MacOS
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# 設定リロード
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# true color対応
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# ── plugins ──────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# 15分ごとに自動保存
set -g @continuum-save-interval '5'

# tmux サーバ起動時に自動復元
set -g @continuum-restore 'on'

# TPM 初期化（必ず末尾に置く）
run '~/.tmux/plugins/tpm/tpm'

# vim/neovim の内容も復元するための設定
set -g @resurrect-strategy-nvim 'session'

# copy mode を vi 風にする。 prefix + [
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

