# 必ずしも起動時に必要でないプラグインは
# 利用条件と共にこちらで入れる

# 補完プラグイン
# インサートモード時に呼び出す
[[plugins]]
repo     = 'Shougo/neocomplete'
on_i     = 1
hook_add = 'source ~/.vim/userautoload/plugins/pg-lang/common/plugin-neocomplete.vim'

# 以下のファイルは、環境に併せてコメントを外してインストールすること

# 特定のファイルタイプで読み込む
## Markdown
[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = 'markdown'

# JavaScript
## ES6のシンタックスを当てる
[[plugins]]
repo  = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

## jsの補完プラグイン
[[plugins]]
repo  = 'mattn/jscomplete-vim'
on_ft = 'javascript'

## gfでrequire()のモジュールにジャンプ
[[plugins]]
repo     = 'moll/vim-node'
on_ft    = 'javascript'
add_hook = 'source ~/.vim/userautoload/plugins/pg-lang/javascript/plugin-javascript.vim'

## node.jsの補完
[[plugins]]
repo  = 'myhere/vim-nodejs-complete'
on_ft = 'javascript'

## function行、もしくは:JsDocでJSDocコメントができる
[[plugins]]
repo  = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

## node用の辞書
[[plugins]]
repo     = 'guileen/vim-node-dict'
on_ft    = 'javascript'
add_hook = 'source ~/.vim/userautoload/plugins/pg-lang/javascript/plugin-javascript.vim'

## jsxのシンタックスプラグイン
[[plugins]]
repo  = 'mxw/vim-jsx'
on_ft = 'javascript'

## javascriptのsyntaxとindentをよしなに調整してくれる
# 入れるとバグる
#[[plugins]]
#repo = 'pangloss/vim-javascript'
#on_ft = 'javascript'

## Python
[[plugins]]
repo  = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo  = 'andviro/flake8-vim'
on_ft = 'python'

[[plugins]]
repo  = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo  = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo  = 'hachibeeDI/python_hl_lvar.vim'
on_ft = 'python'

[[plugins]]
repo  = 'kana/vim-textobj-indent'
on_ft = 'python'

[[plugins]]
repo  = 'bps/vim-textobj-python'
on_ft = 'python'

[[plugins]]
repo  = 'kana/vim-smartinput'
on_ft = 'python'

[[plugins]]
repo  = 'Flake8-vim'
on_ft = 'python'

#[[plugins]]
#repo = 'altercation/vim-colors-solarized'
#on_cmd = 'colorscheme solarized'
#hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-solarized.vim'

# haskell
[[plugins]]
repo  = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

# これを使うには
# cabal update
# cabal install happy
# export PATH="$HOME/.cabal/bin:$PATH"
# cabal install ghc-mod
# の手順が必要
[[plugins]]
repo  = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

# Haskellの補完プラグイン
[[plugins]]
repo  = 'ujihisa/neco-ghc'
on_ft = 'haskell'

# シンタックス
[[plugins]]
repo  = 'dag/vim2hs'
on_ft = 'haskell'

# hoogle
# cabal install hoogle が必要
[[plugins]]
repo = 'thinca/vim-ref'
on_ft = 'haskell'
[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = 'haskell'


# 有効にならない
#[[plugins]]
#repo = 'thinca/vim-fontzoom'
#on_cmd = ['Fontzoom']
#on_map = ['<Plug>(fontzoom-']
#gui  = 1
#
#[[plugins]]
#repo = 'vim-scripts/zoom.vim'
#gui  = 1
#
# お試し
# minimap
#[[plugins]]
#repo = 'koron/minimap-vim'
#gui  = 1

# カラーテーマ
[[plugins]]
repo = 'altercation/vim-colors-solarized'
on_cmd = ['SOLARIZED']
hook_post_source = '''
  source ~/.vim/userautoload/plugins/basic/plugin-solarized.vim
'''
#[[plugins]]
#repo = 'w0ng/vim-hybrid'
#on_cmd = ['HYBRID']
#hook_post_source = '''
#  source ~/.vim/userautoload/plugins/basic/plugin-hybrid.vim
#'''
