# 秘本は github.com のレポジトリを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行スべきコマンドがある場合は以下のような感じ
# vimで非同期処理を実現するためのプラグイン
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_pudate = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin()'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# カラーテーマ
[[plugins]]
repo = 'w0ng/vim-hybrid'

