# 基本は github.com のレポジトリを指定するだけ
[[plugins]]
repo     = 'Shougo/dein.vim'

# git clone 後、実行スべきコマンドがある場合は以下のような感じ
# vimで非同期処理を実現するためのプラグイン
[[plugins]]
repo     = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# Unite
[[plugins]]
repo     = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-unite.vim'
# Unite history
[[plugins]]
repo     = 'Shougo/neomru.vim'
depends  = ['unite.vim']
# yank/history
[[plugins]]
repo     = 'Shougo/neoyank.vim'
depends  = ['unite.vim']
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-neoyank.vim'

[[plugins]]
repo     = 'Shougo/neosnippet.vim'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-neosnippet.vim'
[[plugins]]
repo     = 'Shougo/neosnippet-snippets'
depends  = ['neosnippet.vim']

# open shell from vim
# write alias to ~/.vimshrc
[[plugins]]
repo     = 'Shougo/vimshell'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-vimshell.vim'

# カラーテーマ
[[plugins]]
repo     = 'w0ng/vim-hybrid'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-color-scheme.vim'
[[plugins]]
repo     = 'altercation/vim-colors-solarized'

# Git操作
[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-fugitive.vim'
[[plugins]]
repo     = 'gregsexton/gitv'
depends  = ['vim-fugitive']
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-gitv.vim'
[[plugins]]
repo     = 'cohama/agit.vim'

# ステータスラインのカスタマイズのためのプラグイン
[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-lightline.vim'
# lightline.vimと連携しているgitプラグイン
[[plugins]]
repo     = 'airblade/vim-gitgutter'

# インデント行を可視化するプラグイン
[[plugins]]
repo     = 'nathanaelkane/vim-indent-guides'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-indent-guides.vim'

# 連続入力を補助するプラグイン
# ウィンドウサイズの調整などに使用
[[plugins]]
repo     = 'kana/vim-submode'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-submode.vim'

# シンタックスプラグイン
[[plugins]]
repo     = 'scrooloose/syntastic'

# ファイラー系
[[plugins]]
repo     = 'Shougo/vimfiler'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-vimfiler.vim'
[[plugins]]
repo     = 'ctrlpvim/ctrlp.vim'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-ctrlp.vim'

# テキストオブジェクト操作
[[plugins]]
repo     = 'kana/vim-operator-replace.git'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-operator-replace.vim'
[[plugins]]
repo     = 'kana/vim-operator-user.git'
[[plugins]]
repo     = 'tpope/vim-surround'

# Markdown用のプラグイン
# Markdownプレビューができるプラグイン
[[plugins]]
repo     = 'kannokanno/previm'
[[plugins]]
repo     = 'tyru/open-browser.vim'
hook_add = 'source ~/.vim/userautoload/plugins/basic/plugin-open-browser.vim'

[[plugins]]
repo     = 'thinca/vim-template'

[[plugins]]
repo     = 'thinca/vim-quickrun'

